/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db_tarjeta;

import java.awt.HeadlessException;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.Connection;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Carlos
 */
public class FormTarjetaCredito extends javax.swing.JFrame {

    /**
     * Creates new form FormTarjetaCredito
     */
    
    Connection conectar = Conexion.MySQLConnect();
    
    private JTable tblTabla = new JTable();
    private DefaultTableModel dtm = new DefaultTableModel();
    
    
    public FormTarjetaCredito() {
        initComponents();
        setLocationRelativeTo(null);
        
        
        dtm.addColumn("Nombre");
        dtm.addColumn("Vencimiento");
        dtm.addColumn("Linea de Crédito");
        dtm.addColumn("Número");
        dtm.addColumn("CVV");
        dtm.addColumn("Banco");
        
        tblTabla = new JTable(dtm);
        
        
        //TextPrompt placeholderNombreCliente = new TextPrompt("Escriba su nombre...", txfNombreCliente);
    }
    
    
    private MaskFormatter crearFormato(String sFormato)
    {
        MaskFormatter formato = null;
        try {
        formato = new MaskFormatter("####-####-####-####");
        formato.setValidCharacters("0123456789");
        formato.setPlaceholderCharacter('X');
        formato.setAllowsInvalid(false);
        }
        catch(java.text.ParseException exc){
            
        }
        
        return formato;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlMain1 = new javax.swing.JPanel();
        lblEncabezado1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txfNombreCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        dtcFechaVencimiento = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        cbxBanco = new javax.swing.JComboBox<>();
        cbxLineaCredito = new javax.swing.JComboBox<>();
        btnEnviar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        lblEncabezado = new javax.swing.JLabel();
        ftfNumeroTarjeta = new javax.swing.JFormattedTextField();
        ftfCVV = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setForeground(new java.awt.Color(255, 255, 255));
        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMain1.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain1.setForeground(new java.awt.Color(255, 255, 255));
        pnlMain1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEncabezado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Screenshot 2021-09-24 142110.png"))); // NOI18N
        lblEncabezado1.setToolTipText("");
        pnlMain1.add(lblEncabezado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-valor-de-verificación-de-la-tarjeta-50.png"))); // NOI18N
        pnlMain1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));

        txfNombreCliente.setBorder(null);
        pnlMain1.add(txfNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 280, 30));

        jLabel9.setText("*Nombre del Cliente");
        pnlMain1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 280, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel10.setText("Formulario Tarjeta de Crédito");
        pnlMain1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        jLabel12.setText("*Banco");
        pnlMain1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 280, -1));
        pnlMain1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 770, 10));

        dtcFechaVencimiento.setBackground(new java.awt.Color(255, 255, 255));
        dtcFechaVencimiento.setDateFormatString("dd/MM/yyyy");
        pnlMain1.add(dtcFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 280, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-bank-64.png"))); // NOI18N
        pnlMain1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, -1, -1));

        jLabel5.setText("*CVV");
        pnlMain1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 280, -1));

        jLabel2.setText("*Número de tarjeta o número de cuenta");
        pnlMain1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 280, -1));
        pnlMain1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 280, -1));
        pnlMain1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 280, -1));
        pnlMain1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 317, 280, -1));
        pnlMain1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 417, 280, -1));
        pnlMain1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 280, -1));
        pnlMain1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 280, -1));

        cbxBanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "HSBC", "Banorte", "BBVA", "Scotiabank", "Banamex", "Inbursa", "IXE" }));
        cbxBanco.setBorder(null);
        pnlMain1.add(cbxBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 280, 30));

        cbxLineaCredito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "1000", "3000", "5000", "10000", "20000", "50000", "100000" }));
        cbxLineaCredito.setBorder(null);
        pnlMain1.add(cbxLineaCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 280, 30));

        btnEnviar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-añadir-24.png"))); // NOI18N
        btnEnviar.setText("  Enviar Datos");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        pnlMain1.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 180, 40));
        pnlMain1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 790, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("Formulario Tarjeta de Crédito");
        pnlMain1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        lblEncabezado.setIcon(new javax.swing.ImageIcon("C:\\Dev\\Learning\\Java\\ULSA\\resources\\Screenshot 2021-09-24 142110.png")); // NOI18N
        lblEncabezado.setToolTipText("");
        pnlMain1.add(lblEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        ftfNumeroTarjeta.setBorder(null);
        try {
            ftfNumeroTarjeta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfNumeroTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfNumeroTarjetaActionPerformed(evt);
            }
        });
        pnlMain1.add(ftfNumeroTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 280, 30));

        ftfCVV.setBorder(null);
        try {
            ftfCVV.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnlMain1.add(ftfCVV, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 280, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-usuario-50.png"))); // NOI18N
        pnlMain1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-fecha-hasta-50.png"))); // NOI18N
        pnlMain1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-dólar-estadounidense-50.png"))); // NOI18N
        pnlMain1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-parte-trasera-de-tarjeta-bancaria-50.png"))); // NOI18N
        pnlMain1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        jLabel13.setText("*Fecha de vencimiento");
        pnlMain1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 280, -1));

        jLabel18.setText("*Monto de la línea de Crédito");
        pnlMain1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 280, -1));

        pnlMain.add(pnlMain1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 540));

        getContentPane().add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        
        DateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
        
        try { 
            /**** Validación de datos ****/    
                
            String mensajeError = "";
            
            if (txfNombreCliente.getText().equals(""))      mensajeError += "\n-Nombre del Cliente";
            if (dtcFechaVencimiento.getDate() == null)      mensajeError += "\n-Fecha de Vencimento";
            if (cbxLineaCredito.getSelectedIndex() == 0)    mensajeError += "\n-Monto de la línea de crédito";
            if (ftfNumeroTarjeta.getText().contains(" "))   mensajeError += "\n-Número de tarjeta";
            if (ftfCVV.getText().contains(" "))             mensajeError += "\n-Código de validación (CVV)";
            if (cbxBanco.getSelectedIndex() == 0)           mensajeError += "\n-Banco";
            
            if (!mensajeError.equals("")) throw new Exception(mensajeError);
            
            
            /**** Envío de datos a la base de datos ****/
            
            String insertar = "INSERT INTO db_tarjeta VALUES(?,?,?,?,?,?)";
            PreparedStatement ps = (PreparedStatement)conectar.prepareStatement(insertar);
            
            if (JOptionPane.OK_OPTION == JOptionPane.showConfirmDialog(null,
                "Desea enviar los datos?", "", JOptionPane.YES_NO_OPTION))
            {
                ps.setString(1, txfNombreCliente.getText());
                ps.setString(2, formatoFecha.format(dtcFechaVencimiento.getDate()));
                ps.setString(3, cbxLineaCredito.getSelectedItem().toString());
                ps.setString(4, ftfNumeroTarjeta.getText());
                ps.setString(5, ftfCVV.getText());
                ps.setString(6, cbxBanco.getSelectedItem().toString());
            
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, 
                        "Los datos fueron registrados con éxito!");
            
                txfNombreCliente.setText("");
                dtcFechaVencimiento.setDate(null);
                cbxLineaCredito.setSelectedIndex(0);
                ftfNumeroTarjeta.setText("");
                ftfCVV.setText("");
                cbxBanco.setSelectedIndex(0);
            }
            
            
        } catch (HeadlessException | SQLException exc) {
            JOptionPane.showMessageDialog(null, 
                    "Error al registrar en la base de datos: " + exc.getMessage(),
                    "Error!!!", JOptionPane.ERROR_MESSAGE);
            
        } catch(Exception exc) {
            JOptionPane.showMessageDialog(null,
                    "Faltan datos por registrar o se introdujeron de forma incorrecta:\n" + exc.getMessage() + "\n\n",
                    "Error!!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

/* Este handler fue añadido por error, pero no lo puedo borrar porque netbeans es tonto */
    private void ftfNumeroTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfNumeroTarjetaActionPerformed
    }//GEN-LAST:event_ftfNumeroTarjetaActionPerformed


    /**
     * @param args the command line arguments
     */ 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTarjetaCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTarjetaCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTarjetaCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTarjetaCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTarjetaCredito().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JComboBox<String> cbxBanco;
    private javax.swing.JComboBox<String> cbxLineaCredito;
    private com.toedter.calendar.JDateChooser dtcFechaVencimiento;
    private javax.swing.JFormattedTextField ftfCVV;
    private javax.swing.JFormattedTextField ftfNumeroTarjeta;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblEncabezado;
    private javax.swing.JLabel lblEncabezado1;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMain1;
    private javax.swing.JTextField txfNombreCliente;
    // End of variables declaration//GEN-END:variables
}
